
import type { Metadata } from "next";

import "./globals.css";
import { UserProvider } from '../lib/UserContext';



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  metadataBase: new URL(process.env.NEXT_PUBLIC_APP_URL || 'https://voz-segura.com'),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-['Segoe_UI',Tahoma,Geneva,Verdana,sans-serif]"
      >
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}