-- Schema para la tabla de suscripciones a eventos

-- Tabla de suscripciones a eventos
CREATE TABLE public.event_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    UNIQUE(event_id, user_id)
);

-- Índice para consultas de suscripciones por usuario
CREATE INDEX idx_event_subscriptions_user_id ON public.event_subscriptions(user_id);

-- Políticas de seguridad
ALTER TABLE public.event_subscriptions ENABLE ROW LEVEL SECURITY;

-- Cualquiera puede ver las suscripciones a eventos
CREATE POLICY "Event subscriptions visible para todos" ON public.event_subscriptions
    FOR SELECT USING (true);

-- Solo el usuario propietario puede crear o eliminar sus suscripciones
CREATE POLICY "Event subscriptions gestionables por usuario" ON public.event_subscriptions
    FOR INSERT WITH CHECK (auth.uid() = user_id);
    
CREATE POLICY "Event subscriptions eliminables por usuario" ON public.event_subscriptions
    FOR DELETE USING (auth.uid() = user_id);
